  feat/DOB[m
  feat/MedicalRecord-Preview-Doctor[m
  feat/MedicalRecordAccess-Log[m
* [32mfeat/RAG[m
  feat/Record-Lookup[m
  feat/SignalR[m
  feat/UI-Improvement[m
  feat/UI-enhancement[m
  feat/UI-pdf-enhancement[m
  feat/admin-features[m
  feat/auth-UI-integration[m
  feat/doctor-selection[m
  feat/edit-profile[m
  feat/export-feature[m
  feat/followup[m
  feat/labs[m
  feat/merge-test[m
  feat/new-features[m
  feat/prevent-multibooking[m
  feat/rating[m
  feat/refactor[m
  feat/report_to_email[m
  fix/login[m
  fix/network-issue[m
  fix/refine_UI[m
  main[m
  rating[m
  refactor/UI[m
  refactor/UI-enhancement[m
